services:
  - type: web
    name: white-label-advisors
    runtime: static
    buildCommand: ""
    staticPublishPath: .
    pullRequestPreviewsEnabled: true
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
